version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./../postgres_volumes:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py makemigrations &&
                      python manage.py collectstatic
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000  &&
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  redis:
    image: redis:alpine
    depends_on:
      - db

  celery:
      build: .
      command: celery -A blog worker -l info
      volumes:
          - ./:/usr/src/app/
      depends_on:
        - web
        - redis
  celery-beat:
    build: .
    command: celery -A blog beat
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - web
      - redis
